[tool.poetry]
name = "mastermind"
version = "0.1.0"
description = ""
authors = ["Olof Mattsson <olof.mattsson103@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
